server.port=${PORT:8080}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=bonkurinaveen071@gmail.com
spring.mail.password=admin123
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.address=0.0.0.0

